export const CHART_RANGES = {
  INTRADAY: '1d',
  WEEK: '5d',
  MONTH: '1mo',
  HALF_YEAR: '6mo',
  YEAR_TO_DATE: 'ytd',
  YEAR: '1y',
  FIVE_YEARS: '5y',
  MAX: 'max'
}

export const CHART_INTERVALS = {
  AUTO: 'auto',
  FIVE_MINUTES: '5m',
  FIFTEEN_MINUTES: '15m',
  HOUR: '1h',
  DAY: '1d',
  WEEK: '1wk',
  MONTH: '1mo'
}

export const CHART_INTERVALS_BY_RANGE = {
  [CHART_RANGES.INTRADAY]: [CHART_INTERVALS.AUTO, CHART_INTERVALS.FIVE_MINUTES, CHART_INTERVALS.FIFTEEN_MINUTES, CHART_INTERVALS.HOUR],
  [CHART_RANGES.WEEK]: [CHART_INTERVALS.AUTO, CHART_INTERVALS.FIVE_MINUTES, CHART_INTERVALS.FIFTEEN_MINUTES, CHART_INTERVALS.HOUR],
  [CHART_RANGES.MONTH]: [CHART_INTERVALS.AUTO, CHART_INTERVALS.FIFTEEN_MINUTES, CHART_INTERVALS.HOUR, CHART_INTERVALS.DAY],
  [CHART_RANGES.HALF_YEAR]: [CHART_INTERVALS.AUTO, CHART_INTERVALS.HOUR, CHART_INTERVALS.DAY, CHART_INTERVALS.WEEK],
  [CHART_RANGES.YEAR_TO_DATE]: [CHART_INTERVALS.AUTO, CHART_INTERVALS.HOUR, CHART_INTERVALS.DAY, CHART_INTERVALS.WEEK],
  [CHART_RANGES.YEAR]: [CHART_INTERVALS.AUTO, CHART_INTERVALS.DAY, CHART_INTERVALS.WEEK],
  [CHART_RANGES.FIVE_YEARS]: [CHART_INTERVALS.AUTO, CHART_INTERVALS.DAY, CHART_INTERVALS.WEEK, CHART_INTERVALS.MONTH],
  [CHART_RANGES.MAX]: [CHART_INTERVALS.AUTO, CHART_INTERVALS.WEEK, CHART_INTERVALS.MONTH]
}

export const CHART_INTERVALS_MAX_GAP = {
  [CHART_INTERVALS.FIVE_MINUTES]: 3600 * 1000,
  [CHART_INTERVALS.FIFTEEN_MINUTES]: 2 * 3600 * 1000,
  [CHART_INTERVALS.HOUR]: 6 * 3600 * 1000,
  [CHART_INTERVALS.DAY]: null,
  [CHART_INTERVALS.WEEK]: null,
  [CHART_INTERVALS.MONTH]: null
}

export const TRANSACTION_TYPES = {
  BUY: 'buy',
  SELL: 'sell'
}

export const CHART_RANGES_MAX_GAP = {
  [CHART_RANGES.INTRADAY]: 3600 * 1000,
  [CHART_RANGES.WEEK]: 2 * 3600 * 1000,
  [CHART_RANGES.MONTH]: 6 * 3600 * 1000,
  [CHART_RANGES.HALF_YEAR]: null,
  [CHART_RANGES.YEAR_TO_DATE]: null,
  [CHART_RANGES.YEAR]: null,
  [CHART_RANGES.FIVE_YEARS]: null,
  [CHART_RANGES.MAX]: null
}

export const FINANCE_PROVIDER = {
  YAHOO: 'yahoo',
  EAST_MONEY: 'eastmoney'
}

export const MARKET_STATES = {
  PRE: 'PRE',
  PRE_WITHOUT_DATA: 'POST_WITHOUT_DATA',
  POST: 'POST',
  POST_WITHOUT_DATA: 'POST_WITHOUT_DATA',
  REGULAR: 'REGULAR'
}

export const CHART_RANGES_IN_DAYS = {
  INTRADAY: 1,
  WEEK: 7,
  MONTH: 30,
  HALF_YEAR: 6 * 30,
  YEAR_TO_DATE: 'ytd',
  YEAR: 365,
  FIVE_YEARS: 5 * 365,
  MAX: 10 * 365
}
